# Generated by Django 5.2.6 on 2026-04-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashops", "0008_sucursal_razon_social"),
        ("users", "0003_user_dni_user_legajo_user_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sucursal_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_base",
                to="cashops.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="usuario_fijo",
            field=models.BooleanField(default=False, verbose_name="Usuario fijo"),
        ),
    ]
