# Generated by Django 5.2.6 on 2026-04-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_usuario_fijo_user_sucursal_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legajo',
        ),
    ]
