# Generated by Codex on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion


MODULES = ("cashops", "config", "treasury", "users")
ADMIN_CODES = {"ADMIN", "ADMINISTRADOR"}


def seed_role_permissions(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    RolePermission = apps.get_model("users", "RolePermission")
    for role in Role.objects.all():
        is_admin = (role.code or "").strip().upper() in ADMIN_CODES
        for module in MODULES:
            can_access = is_admin or module == "cashops"
            RolePermission.objects.get_or_create(
                role=role,
                module=module,
                defaults={"can_read": can_access, "can_write": can_access},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module", models.CharField(choices=[("cashops", "Caja operativa"), ("config", "Configuracion"), ("treasury", "Tesoreria"), ("users", "Usuarios")], max_length=20)),
                ("can_read", models.BooleanField(default=False)),
                ("can_write", models.BooleanField(default=False)),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permissions", to="users.role")),
            ],
            options={
                "ordering": ["role__name", "module"],
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module", models.CharField(choices=[("cashops", "Caja operativa"), ("config", "Configuracion"), ("treasury", "Tesoreria"), ("users", "Usuarios")], max_length=20)),
                ("can_read", models.BooleanField(default=False)),
                ("can_write", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permission_overrides", to="users.user")),
            ],
            options={
                "ordering": ["user__username", "module"],
            },
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(fields=("role", "module"), name="unique_role_permission_per_module"),
        ),
        migrations.AddConstraint(
            model_name="userpermission",
            constraint=models.UniqueConstraint(fields=("user", "module"), name="unique_user_permission_per_module"),
        ),
        migrations.RunPython(seed_role_permissions, migrations.RunPython.noop),
    ]
