# Generated by Django 5.2.6 on 2026-05-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0016_add_canal_planificacion'),
        ('users', '0007_rolepermission_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_principales', to='cashops.empresa', verbose_name='Empresa principal'),
        ),
        migrations.AddField(
            model_name='user',
            name='empresas_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_acceso', to='cashops.empresa', verbose_name='Empresas con acceso'),
        ),
    ]
