# Generated by Django 5.2.6 on 2026-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_utf8_spanish_user_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
    ]
