# Generated by Django 5.2.6 on 2026-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_rolepermission_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('cashops_validate', 'Validación de efectivo'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('cashops_validate', 'Validación de efectivo'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
    ]
