# Generated by Django 5.2.6 on 2026-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_seed_cajero_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('cashops_validate', 'Validación de efectivo'), ('cashops_debt_closed', 'Cargar deuda en caja cerrada'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('cashops_validate', 'Validación de efectivo'), ('cashops_debt_closed', 'Cargar deuda en caja cerrada'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
    ]
