# Generated by Django 5.2.6 on 2026-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0021_cajavalidacion_caja_validacion_estado_and_more'),
        ('users', '0013_alter_rolepermission_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursales_deuda',
            field=models.ManyToManyField(blank=True, related_name='usuarios_carga_deuda', to='cashops.sucursal', verbose_name='Sucursales adicionales para cargar deuda'),
        ),
    ]
