# Generated by Django 5.2.6 on 2026-07-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_sucursales_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('cashops_validate', 'Validación de efectivo'), ('cashops_debt_closed', 'Cargar deuda en caja cerrada'), ('cashops_mov_del', 'Eliminar movimientos de caja'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('cashops', 'Caja operativa'), ('cashops_closed_fix', 'Corrección de cajas cerradas'), ('cashops_validate', 'Validación de efectivo'), ('cashops_debt_closed', 'Cargar deuda en caja cerrada'), ('cashops_mov_del', 'Eliminar movimientos de caja'), ('config', 'Configuración'), ('treasury', 'Tesorería'), ('users', 'Usuarios')], max_length=20),
        ),
    ]
