# Generated by Django 5.2.6 on 2026-07-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_rolepermission_module_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='rolepermission',
            name='unique_role_permission_per_module',
            constraint=models.UniqueConstraint(fields=('role', 'module'), name='unique_role_permission_per_module', violation_error_message='Este rol ya tiene configurado un permiso para ese módulo.'),
        ),
        migrations.AlterConstraint(
            model_name='userpermission',
            name='unique_user_permission_per_module',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_user_permission_per_module', violation_error_message='Este usuario ya tiene configurado un permiso para ese módulo.'),
        ),
    ]
