# Generated by Django 5.2.6 on 2026-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso_vencimiento_activo', models.BooleanField(default=True, help_text='Si se destilda, el aviso mensual de vencimiento del servicio de alojamiento no se muestra a ningun administrador. Volver a tildarlo lo reactiva.', verbose_name='Mostrar aviso de vencimiento del servicio')),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuración del sistema',
            },
        ),
    ]
