# Generated by Django 5.2.6 on 2026-03-27 19:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='cashops.sucursal')),
            ],
            options={
                'ordering': ['-abierta_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_esperado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_fisico', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('AUTO', 'Auto'), ('JUSTIFICADO', 'Justificado')], max_length=15)),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='cashops.caja')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cerrado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='cashops.cierrecaja')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('GASTO', 'Gasto'), ('VENTA_TARJETA', 'Venta tarjeta'), ('TRANSFERENCIA_SALIDA', 'Transferencia salida'), ('TRANSFERENCIA_ENTRADA', 'Transferencia entrada'), ('TRANSFERENCIA_SUCURSAL_SALIDA', 'Transferencia sucursal salida'), ('TRANSFERENCIA_SUCURSAL_ENTRADA', 'Transferencia sucursal entrada'), ('AJUSTE_CIERRE', 'Ajuste de cierre')], max_length=40)),
                ('sentido', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cashops.caja')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='ajuste_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_ajustados', to='cashops.movimientocaja'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRE_CAJAS', 'Entre cajas'), ('ENTRE_SUCURSALES', 'Entre sucursales')], max_length=20)),
                ('clase', models.CharField(choices=[('DINERO', 'Dinero'), ('MERCADERIA', 'Mercaderia')], max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='cashops.caja')),
                ('caja_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='cashops.caja')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='cashops.sucursal')),
                ('sucursal_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='cashops.sucursal')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cashops.transferencia'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operativa', models.DateField()),
                ('tipo', models.CharField(choices=[('TM', 'T.M.'), ('TT', 'T.T.')], max_length=2)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('abierto_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='cashops.sucursal')),
            ],
            options={
                'ordering': ['-fecha_operativa', 'tipo', 'sucursal__nombre'],
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='cashops.turno'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['estado', 'cerrado_en'], name='cashops_cie_estado_239b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['tipo', 'clase'], name='cashops_tra_tipo_a161e5_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['creado_en'], name='cashops_tra_creado__a98886_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja', 'tipo'], name='cashops_mov_caja_id_74ccc6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja', 'creado_en'], name='cashops_mov_caja_id_22c2f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='movement_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['sucursal', 'fecha_operativa', 'tipo'], name='cashops_tur_sucursa_a075f5_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['estado'], name='cashops_tur_estado_b695b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha_operativa', 'tipo'), name='unique_turno_by_branch_date_type'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['estado', 'turno'], name='cashops_caj_estado_3fb04a_idx'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['sucursal', 'estado'], name='cashops_caj_sucursa_fe1e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['usuario', 'estado'], name='cashops_caj_usuario_dae676_idx'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario', 'turno', 'sucursal'), name='unique_open_box_by_user_turn_branch'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.CheckConstraint(condition=models.Q(('monto_inicial__gte', 0)), name='box_initial_amount_non_negative'),
        ),
    ]
