# Generated by Django 5.2.6 on 2026-03-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIFERENCIA_GRAVE', 'Diferencia grave')], default='DIFERENCIA_GRAVE', max_length=30)),
                ('mensaje', models.CharField(max_length=255)),
                ('resuelta', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='cashops.caja')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cashops.cierrecaja')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='cashops.sucursal')),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
                'indexes': [models.Index(fields=['tipo', 'resuelta'], name='cashops_ale_tipo_70207d_idx'), models.Index(fields=['sucursal', 'creada_en'], name='cashops_ale_sucursa_e8a585_idx')],
            },
        ),
    ]
