# Generated by Django 5.2.6 on 2026-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashops", "0002_alertaoperativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientocaja",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("APERTURA", "Apertura"),
                    ("INGRESO_EFECTIVO", "Ingreso efectivo"),
                    ("GASTO", "Gasto"),
                    ("VENTA_TARJETA", "Venta tarjeta"),
                    ("TRANSFERENCIA_SALIDA", "Transferencia salida"),
                    ("TRANSFERENCIA_ENTRADA", "Transferencia entrada"),
                    ("TRANSFERENCIA_SUCURSAL_SALIDA", "Transferencia sucursal salida"),
                    ("TRANSFERENCIA_SUCURSAL_ENTRADA", "Transferencia sucursal entrada"),
                    ("AJUSTE_CIERRE", "Ajuste de cierre"),
                ],
                max_length=40,
            ),
        ),
    ]
