# Generated by Django 5.2.6 on 2026-03-29 22:26

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0003_alter_movimientocaja_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaoperativa',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alertaoperativa',
            name='periodo_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertaoperativa',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='cashops.turno'),
        ),
        migrations.AddField(
            model_name='alertaoperativa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_operativas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertaoperativa',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='cashops.caja'),
        ),
        migrations.AlterField(
            model_name='alertaoperativa',
            name='cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cashops.cierrecaja'),
        ),
        migrations.AlterField(
            model_name='alertaoperativa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='cashops.sucursal'),
        ),
        migrations.AlterField(
            model_name='alertaoperativa',
            name='tipo',
            field=models.CharField(choices=[('DIFERENCIA_GRAVE', 'Diferencia grave'), ('RUBRO_EXCEDIDO', 'Rubro excedido')], default='DIFERENCIA_GRAVE', max_length=30),
        ),
        migrations.CreateModel(
            name='RubroOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'nombre'], name='cashops_rub_activo_42b4ec_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_operational_category_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='LimiteRubroOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_maximo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limites_rubros_operativos', to='cashops.sucursal')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='cashops.rubrooperativo')),
            ],
            options={
                'ordering': ['rubro__nombre', 'sucursal__nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='alertaoperativa',
            name='rubro_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='cashops.rubrooperativo'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='rubro_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cashops.rubrooperativo'),
        ),
        migrations.AddIndex(
            model_name='alertaoperativa',
            index=models.Index(fields=['periodo_fecha', 'tipo'], name='cashops_ale_periodo_f5baca_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo', 'rubro_operativo'], name='cashops_mov_tipo_c7f5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='limiterubrooperativo',
            index=models.Index(fields=['sucursal', 'rubro'], name='cashops_lim_sucursa_ae908c_idx'),
        ),
        migrations.AddConstraint(
            model_name='limiterubrooperativo',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', False)), fields=('rubro', 'sucursal'), name='unique_operational_limit_by_branch'),
        ),
        migrations.AddConstraint(
            model_name='limiterubrooperativo',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', True)), fields=('rubro',), name='unique_operational_limit_global'),
        ),
        migrations.AddConstraint(
            model_name='limiterubrooperativo',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_maximo__gt', 0)), name='operational_limit_positive'),
        ),
    ]
