# Generated by Django 5.2.6 on 2026-03-29 23:09

from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


UNCATEGORIZED_OPERATIONAL_CATEGORY_NAME = "Sin clasificar"


def backfill_operational_control_data(apps, schema_editor):
    RubroOperativo = apps.get_model("cashops", "RubroOperativo")
    MovimientoCaja = apps.get_model("cashops", "MovimientoCaja")
    LimiteRubroOperativo = apps.get_model("cashops", "LimiteRubroOperativo")

    category = RubroOperativo.objects.filter(nombre__iexact=UNCATEGORIZED_OPERATIONAL_CATEGORY_NAME).first()
    if category is None:
        category = RubroOperativo.objects.create(
            nombre=UNCATEGORIZED_OPERATIONAL_CATEGORY_NAME,
            activo=False,
            es_sistema=True,
        )
    else:
        updates = {}
        if category.activo:
            updates["activo"] = False
        if not category.es_sistema:
            updates["es_sistema"] = True
        if updates:
            RubroOperativo.objects.filter(pk=category.pk).update(**updates)

    MovimientoCaja.objects.filter(
        tipo="GASTO",
        rubro_operativo__isnull=True,
    ).update(rubro_operativo=category)
    LimiteRubroOperativo.objects.filter(porcentaje_maximo__gt=Decimal("100.00")).update(
        porcentaje_maximo=Decimal("100.00")
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0004_alertaoperativa_dedupe_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrooperativo',
            name='es_sistema',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_operational_control_data, noop_reverse),
        migrations.AddConstraint(
            model_name='limiterubrooperativo',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_maximo__lte', 100)), name='operational_limit_max_100'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'GASTO'), _negated=True), ('rubro_operativo__isnull', False), _connector='OR'), name='expense_requires_operational_category'),
        ),
    ]
