# Generated by Django 5.2.6 on 2026-03-30 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0005_rubrooperativo_es_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='impacta_saldo_caja',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja', 'impacta_saldo_caja', 'creado_en'], name='cashops_mov_caja_id_018dbe_idx'),
        ),
    ]
