# Generated by Django 5.2.6 on 2026-04-11 20:58

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0006_movimientocaja_impacta_saldo_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('APERTURA', 'Apertura'), ('INGRESO_EFECTIVO', 'Ingreso efectivo'), ('GASTO', 'Gasto'), ('VENTA_TARJETA', 'Venta tarjeta (POS)'), ('VENTA_TRANSFERENCIA', 'Venta transferencia'), ('VENTA_PEDIDOSYA', 'Venta PedidosYa'), ('VENTA_QR', 'Venta QR / MercadoPago'), ('TRANSFERENCIA_SALIDA', 'Transferencia salida'), ('TRANSFERENCIA_ENTRADA', 'Transferencia entrada'), ('TRANSFERENCIA_SUCURSAL_SALIDA', 'Transferencia sucursal salida'), ('TRANSFERENCIA_SUCURSAL_ENTRADA', 'Transferencia sucursal entrada'), ('AJUSTE_CIERRE', 'Ajuste de cierre')], max_length=40),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='cashops.rubrooperativo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cashops.producto'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_product_name_ci'),
        ),
    ]
