# Generated by Django 5.2.6 on 2026-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0007_alter_movimientocaja_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='razon_social',
            field=models.CharField(default='', max_length=160),
        ),
    ]
