# Generated by Django 5.2.6 on 2026-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0012_turno_remove_legacy_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('impacta_saldo_caja', models.BooleanField(default=False)),
                ('es_sistema', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['empresa__nombre', 'tipo']},
        ),
        migrations.RenameIndex(
            model_name='caja',
            new_name='cashops_caj_fecha_o_c9f071_idx',
            old_name='cashops_caj_fecha_suc_idx',
        ),
        migrations.RenameIndex(
            model_name='turno',
            new_name='cashops_tur_empresa_1873b3_idx',
            old_name='cashops_tur_empresa_tipo_idx',
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='turno',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('TM', 'Turno Mañana'), ('TT', 'Turno Tarde')], max_length=2),
        ),
    ]
