# Generated by Django 5.2.6 on 2026-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0014_seed_canales_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalingreso',
            name='excluir_de_totales',
            field=models.BooleanField(default=False, help_text='Si está activo, los ingresos de este canal NO se suman al total de ventas digitales ni al efectivo.'),
        ),
    ]
