# Generated by Django 5.2.6 on 2026-06-23 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0018_backfill_negative_closures_to_central_cash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCajaCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('EDICION', 'Edición'), ('ANULACION', 'Anulación')], max_length=12)),
                ('motivo', models.TextField()),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('categoria_anterior', models.CharField(blank=True, max_length=80)),
                ('categoria_nueva', models.CharField(blank=True, max_length=80)),
                ('observacion_anterior', models.CharField(blank=True, max_length=255)),
                ('observacion_nueva', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=12),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja', 'estado'], name='cashops_mov_caja_id_2da30e_idx'),
        ),
        migrations.AddField(
            model_name='movimientocajacorreccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_caja_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocajacorreccion',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='cashops.movimientocaja'),
        ),
        migrations.AddField(
            model_name='movimientocajacorreccion',
            name='rubro_operativo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_como_anterior', to='cashops.rubrooperativo'),
        ),
        migrations.AddField(
            model_name='movimientocajacorreccion',
            name='rubro_operativo_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_como_nuevo', to='cashops.rubrooperativo'),
        ),
        migrations.AddIndex(
            model_name='movimientocajacorreccion',
            index=models.Index(fields=['movimiento', 'creado_en'], name='cashops_mov_movimie_9749db_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocajacorreccion',
            index=models.Index(fields=['accion', 'creado_en'], name='cashops_mov_accion_af727f_idx'),
        ),
    ]
