# Generated by Django 5.2.6 on 2026-06-24 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0019_movimientocajacorreccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=10),
        ),
        migrations.CreateModel(
            name='CajaCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('EDICION', 'Edición'), ('ANULACION', 'Anulación')], max_length=12)),
                ('motivo', models.TextField()),
                ('estado_anterior', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], max_length=10)),
                ('estado_nuevo', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], max_length=10)),
                ('fecha_operativa_anterior', models.DateField()),
                ('fecha_operativa_nueva', models.DateField()),
                ('monto_inicial_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_inicial_nuevo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='cashops.caja')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_caja_completa_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_caja_sucursal_anterior', to='cashops.sucursal')),
                ('sucursal_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_caja_sucursal_nueva', to='cashops.sucursal')),
                ('turno_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_caja_turno_anterior', to='cashops.turno')),
                ('turno_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_caja_turno_nuevo', to='cashops.turno')),
                ('usuario_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_caja_usuario_anterior', to=settings.AUTH_USER_MODEL)),
                ('usuario_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_caja_usuario_nuevo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['caja', 'creado_en'], name='cashops_caj_caja_id_f47d1c_idx'), models.Index(fields=['accion', 'creado_en'], name='cashops_caj_accion_874369_idx')],
            },
        ),
    ]
