# Generated by Django 5.2.6 on 2026-07-10 20:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0020_alter_caja_estado_cajacorreccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VALIDACION', 'Validación'), ('RECHAZO', 'Rechazo')], max_length=15)),
                ('motivo', models.TextField(blank=True)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='validacion_estado',
            field=models.CharField(choices=[('NO_REQUERIDA', 'No requiere validación'), ('PENDIENTE', 'Pendiente de validación'), ('RECHAZADA', 'Validación rechazada'), ('VALIDADA', 'Validada')], default='NO_REQUERIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='caja',
            name='validada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='validada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['estado', 'validacion_estado'], name='cashops_caj_estado_b68713_idx'),
        ),
        migrations.AddField(
            model_name='cajavalidacion',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='cashops.caja'),
        ),
        migrations.AddField(
            model_name='cajavalidacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_de_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cajavalidacion',
            index=models.Index(fields=['caja', 'accion'], name='cashops_caj_caja_id_d39431_idx'),
        ),
    ]
