# Generated by Django 5.2.6 on 2026-07-23 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0021_cajavalidacion_caja_validacion_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caja',
            name='unique_open_box_by_user_turn_branch',
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario', 'turno', 'sucursal', 'fecha_operativa'), name='unique_open_box_by_user_turn_branch_date'),
        ),
    ]
