# Generated by Django 5.2.6 on 2026-07-26 02:25

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0022_remove_caja_unique_open_box_by_user_turn_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='caja',
            name='box_initial_amount_non_negative',
            constraint=models.CheckConstraint(condition=models.Q(('monto_inicial__gte', 0)), name='box_initial_amount_non_negative', violation_error_message='El monto inicial de la caja no puede ser negativo.'),
        ),
        migrations.AlterConstraint(
            model_name='caja',
            name='unique_open_box_by_user_turn_branch_date',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario', 'turno', 'sucursal', 'fecha_operativa'), name='unique_open_box_by_user_turn_branch_date', violation_error_message='Ya existe una caja abierta para ese usuario en este turno, sucursal y fecha.'),
        ),
        migrations.AlterConstraint(
            model_name='limiterubrooperativo',
            name='unique_operational_limit_by_branch',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', False)), fields=('rubro', 'sucursal'), name='unique_operational_limit_by_branch', violation_error_message='Ya existe un límite para ese rubro en esa sucursal.'),
        ),
        migrations.AlterConstraint(
            model_name='limiterubrooperativo',
            name='unique_operational_limit_global',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', True)), fields=('rubro',), name='unique_operational_limit_global', violation_error_message='Ya existe un límite global para ese rubro.'),
        ),
        migrations.AlterConstraint(
            model_name='limiterubrooperativo',
            name='operational_limit_positive',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_maximo__gt', 0)), name='operational_limit_positive', violation_error_message='El porcentaje máximo debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='limiterubrooperativo',
            name='operational_limit_max_100',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_maximo__lte', 100)), name='operational_limit_max_100', violation_error_message='El porcentaje máximo no puede superar 100%.'),
        ),
        migrations.AlterConstraint(
            model_name='movimientocaja',
            name='movement_amount_positive',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='movement_amount_positive', violation_error_message='El monto del movimiento debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='movimientocaja',
            name='expense_requires_operational_category',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'GASTO'), _negated=True), ('rubro_operativo__isnull', False), _connector='OR'), name='expense_requires_operational_category', violation_error_message='El rubro es obligatorio para gastos operativos.'),
        ),
        migrations.AlterConstraint(
            model_name='producto',
            name='unique_product_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_product_name_ci', violation_error_message='Ya existe un producto con ese nombre.'),
        ),
        migrations.AlterConstraint(
            model_name='rubrooperativo',
            name='unique_operational_category_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_operational_category_name_ci', violation_error_message='Ya existe un rubro con ese nombre.'),
        ),
        migrations.AlterConstraint(
            model_name='turno',
            name='unique_turno_per_empresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo'), name='unique_turno_per_empresa', violation_error_message='Ya existe ese turno para esta empresa.'),
        ),
    ]
