# Generated by Django 5.2.6 on 2026-07-27 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0023_alter_caja_box_initial_amount_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='token_alta',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token de alta'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('token_alta__isnull', False)), fields=('token_alta',), name='unique_movement_creation_token', violation_error_message='Este movimiento ya fue registrado.'),
        ),
    ]
