# Generated by Django 5.2.6 on 2026-08-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0024_movimientocaja_token_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajavalidacion',
            name='accion',
            field=models.CharField(choices=[('VALIDACION', 'Validación'), ('RECHAZO', 'Rechazo'), ('REVERSION', 'Reversión de validación')], max_length=15),
        ),
    ]
