# Generated by Django 5.2.6 on 2026-08-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0025_alter_cajavalidacion_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajavalidacion',
            name='accion',
            field=models.CharField(choices=[('VALIDACION', 'Validación'), ('RECHAZO', 'Rechazo'), ('REVERSION', 'Reversión de validación'), ('CORRECCION', 'Corrección del efectivo declarado')], max_length=15),
        ),
    ]
