# Generated by Django 5.2.6 on 2026-08-03 15:43

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0026_alter_cajavalidacion_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de rubros',
                'verbose_name_plural': 'Grupos de rubros',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'nombre'], name='cashops_gru_activo_b6ae8f_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_rubro_group_name_ci', violation_error_message='Ya existe un grupo con ese nombre.')],
            },
        ),
        migrations.AddField(
            model_name='rubrooperativo',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si tiene grupo, el rubro se muestra dentro de ese grupo en la situacion economica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros', to='cashops.gruporubro', verbose_name='Grupo de lectura'),
        ),
        migrations.AddIndex(
            model_name='rubrooperativo',
            index=models.Index(fields=['grupo', 'nombre'], name='cashops_rub_grupo_i_9c4523_idx'),
        ),
    ]
