from django.urls import path

from . import views

app_name = "cashops"

urlpatterns = [
    path("operacion/", views.dashboard, name="dashboard"),
    path("alertas/resolver/<int:alert_id>/", views.resolve_alert, name="resolve_alert"),
    path("alertas/", views.alert_panel, name="alert_panel"),
    path("gestion/matriz/", views.management_matrix, name="management_matrix"),
    path("gestion/matriz/exportar/", views.management_matrix_export, name="management_matrix_export"),
    path("rubros/", views.operational_category_list, name="operational_category_list"),
    path("rubros/nuevo/", views.operational_category_create, name="operational_category_create"),
    path("rubros/<int:category_id>/editar/", views.operational_category_update, name="operational_category_update"),
    path("rubros/<int:category_id>/toggle/", views.operational_category_toggle, name="operational_category_toggle"),
    path("grupos-de-rubros/", views.rubro_group_list, name="rubro_group_list"),
    path("grupos-de-rubros/nuevo/", views.rubro_group_create, name="rubro_group_create"),
    path("grupos-de-rubros/<int:group_id>/editar/", views.rubro_group_update, name="rubro_group_update"),
    path("grupos-de-rubros/<int:group_id>/toggle/", views.rubro_group_toggle, name="rubro_group_toggle"),
    path("limites-rubros/", views.operational_limit_list, name="operational_limit_list"),
    path("limites-rubros/nuevo/", views.operational_limit_create, name="operational_limit_create"),
    path("limites-rubros/<int:limit_id>/editar/", views.operational_limit_update, name="operational_limit_update"),
    path("sucursales/", views.sucursal_list, name="sucursal_list"),
    path("sucursales/nueva/", views.sucursal_create, name="sucursal_create"),
    path("sucursales/<int:sucursal_id>/editar/", views.sucursal_update, name="sucursal_update"),
    path("sucursales/<int:sucursal_id>/toggle/", views.sucursal_toggle, name="sucursal_toggle"),
    path("empresas/", views.empresa_list, name="empresa_list"),
    path("empresas/nueva/", views.empresa_create, name="empresa_create"),
    path("empresas/<int:empresa_id>/editar/", views.empresa_update, name="empresa_update"),
    path("empresas/<int:empresa_id>/toggle/", views.empresa_toggle, name="empresa_toggle"),
    path("empresas/activar/", views.set_empresa_activa, name="set_empresa_activa"),
    path("empresas/seleccionar/", views.set_empresas_activas, name="set_empresas_activas"),
    path("turnos/", views.turno_list, name="turno_list"),
    path("turnos/nuevo/", views.turno_create, name="turno_create"),
    path("cajas/seguimiento/", views.box_tracking_view, name="box_tracking"),
    path("cajas/validaciones/", views.box_validation_queue, name="box_validation_queue"),
    path("cajas/<int:box_id>/validar/", views.box_validate_view, name="box_validate"),
    path("cajas/<int:box_id>/rechazar/", views.box_reject_view, name="box_reject"),
    path("cajas/<int:box_id>/validacion/revertir/", views.box_validation_undo_view, name="box_validation_undo"),
    path("cajas/<int:box_id>/cierre/declarado/", views.box_declared_cash_edit_view, name="box_declared_cash_edit"),
    path("cajas/nueva/", views.open_box_view, name="box_open"),
    path("cajas/<int:box_id>/detalle/", views.box_detail_view, name="box_detail"),
    path("cajas/<int:box_id>/editar/", views.box_edit_view, name="box_edit"),
    path("cajas/<int:box_id>/eliminar/", views.box_delete_view, name="box_delete"),
    path("cajas/movimientos/<int:movement_id>/editar/", views.closed_box_movement_edit_view, name="closed_box_movement_edit"),
    path("cajas/movimientos/<int:movement_id>/eliminar/", views.box_movement_delete_view, name="box_movement_delete"),
    path("cajas/deudas/<int:debt_id>/eliminar/", views.box_debt_delete_view, name="box_debt_delete"),
    path("cajas/<int:box_id>/gasto/", views.register_expense_view, name="box_expense"),
    path("cajas/<int:box_id>/gasto-deuda/", views.register_box_expense_debt_view, name="box_expense_debt"),
    path("cajas/<int:box_id>/venta/", views.register_sale_view, name="register_sale"),
    path("cajas/<int:box_id>/ingreso/", views.register_cash_income_view, name="box_income"),
    path("cajas/<int:box_id>/cerrar/preview/", views.close_box_preview, name="box_close_preview"),
    path("cajas/<int:box_id>/cerrar/", views.close_box_view, name="box_close"),
    path("traspasos/cajas/", views.transfer_between_boxes_view, name="transfer_boxes"),
    path("traspasos/sucursales/", views.transfer_between_branches_view, name="transfer_branches"),
    path("canales-ingreso/", views.canal_ingreso_list, name="canal_ingreso_list"),
    path("canales-ingreso/nuevo/", views.canal_ingreso_create, name="canal_ingreso_create"),
    path("canales-ingreso/<int:canal_id>/editar/", views.canal_ingreso_update, name="canal_ingreso_update"),
    path("canales-ingreso/<int:canal_id>/toggle/", views.canal_ingreso_toggle, name="canal_ingreso_toggle"),
    path("config/reiniciar/", views.reset_operational_data, name="reset_operational_data"),
]
