# Generated by Django 5.2.6 on 2026-03-30 01:58

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('banco', models.CharField(max_length=120)),
                ('tipo_cuenta', models.CharField(choices=[('CA', 'Caja de ahorro'), ('CC', 'Cuenta corriente')], max_length=2)),
                ('numero_cuenta', models.CharField(max_length=40)),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('cbu', models.CharField(blank=True, max_length=22)),
                ('sucursal_bancaria', models.CharField(blank=True, max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_bancarias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['banco', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160)),
                ('referencia_comprobante', models.CharField(blank=True, max_length=60)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_por_pagar_anuladas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_por_pagar_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'proveedor__razon_social', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PagoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('ECHEQ', 'ECHEQ')], max_length=20)),
                ('fecha_pago', models.DateField()),
                ('fecha_diferida', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_tesoreria_anulados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_tesoreria_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='treasury.cuentabancaria')),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='treasury.cuentaporpagar')),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=160)),
                ('identificador_fiscal', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alias_bancario', models.CharField(blank=True, max_length=80)),
                ('cbu', models.CharField(blank=True, max_length=22)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='treasury.proveedor'),
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['activa', 'banco'], name='treasury_cu_activa_80a2c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('cbu'), condition=models.Q(('cbu', ''), _negated=True), name='unique_bank_account_cbu_ci'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('banco'), models.F('numero_cuenta'), name='unique_bank_account_number_per_bank'),
        ),
        migrations.AddIndex(
            model_name='pagotesoreria',
            index=models.Index(fields=['cuenta_por_pagar', 'estado'], name='treasury_pa_cuenta__244623_idx'),
        ),
        migrations.AddIndex(
            model_name='pagotesoreria',
            index=models.Index(fields=['cuenta_bancaria', 'fecha_pago'], name='treasury_pa_cuenta__9751cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pagotesoreria',
            index=models.Index(fields=['fecha_pago', 'medio_pago'], name='treasury_pa_fecha_p_82f091_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagotesoreria',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='treasury_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='pagotesoreria',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia', ''), _negated=True), fields=('cuenta_bancaria', 'medio_pago', 'referencia'), name='unique_payment_reference_per_bank_method'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['activo', 'razon_social'], name='treasury_pr_activo_919b9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('razon_social'), name='unique_supplier_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('identificador_fiscal'), condition=models.Q(('identificador_fiscal', ''), _negated=True), name='unique_supplier_tax_id_ci'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='treasury_cu_estado_f7c273_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['proveedor', 'fecha_vencimiento'], name='treasury_cu_proveed_4da514_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.CheckConstraint(condition=models.Q(('importe_total__gt', 0)), name='payable_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', 0)), name='payable_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__lte', models.F('importe_total'))), name='payable_balance_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gte', models.F('fecha_emision'))), name='payable_due_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_comprobante', ''), _negated=True), fields=('proveedor', 'referencia_comprobante'), name='unique_payable_reference_by_supplier'),
        ),
    ]
