# Generated by Django 5.2.6 on 2026-03-30 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_pagotesoreria_estado_bancario_observacion_bancaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcreditacionTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=80)),
                ('referencia_externa', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-movimiento_bancario__fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IIBB', 'IIBB'), ('COMISION', 'Comision'), ('OTRO', 'Otro')], max_length=16)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.CharField(max_length=160)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['acreditacion_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LotePOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lote', models.DateField()),
                ('terminal', models.CharField(blank=True, max_length=80)),
                ('operador', models.CharField(blank=True, max_length=80)),
                ('total_lote', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_lote', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Debito'), ('CREDITO', 'Credito')], max_length=10)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('ACREDITACION_TARJETA', 'Acreditacion tarjeta'), ('PAGO_TESORERIA', 'Pago tesoreria')], default='MANUAL', max_length=24)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(max_length=160)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='categoriacuentapagar',
            new_name='treasury_ca_activo_4cb472_idx',
            old_name='treasury_ca_activo_5d7d9c_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaporpagar',
            new_name='treasury_cu_categor_c7876b_idx',
            old_name='treasury_cu_categ_6d0c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='pagotesoreria',
            new_name='treasury_pa_estado__a0ae0e_idx',
            old_name='treasury_pa_estado_c_f8d0c3_idx',
        ),
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acreditaciones_tarjeta_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentoacreditacion',
            name='acreditacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos', to='treasury.acreditaciontarjeta'),
        ),
        migrations.AddField(
            model_name='descuentoacreditacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_acreditacion_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotepos',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_pos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotepos',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pos', to='treasury.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='lote_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acreditaciones', to='treasury.lotepos'),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='treasury.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='pago_tesoreria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_bancario', to='treasury.pagotesoreria'),
        ),
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='movimiento_bancario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acreditacion_tarjeta', to='treasury.movimientobancario'),
        ),
        migrations.AddIndex(
            model_name='descuentoacreditacion',
            index=models.Index(fields=['tipo', 'creado_en'], name='treasury_de_tipo_468c9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='descuentoacreditacion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='accreditation_discount_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='lotepos',
            index=models.Index(fields=['fecha_lote', 'operador'], name='treasury_lo_fecha_l_eb49cd_idx'),
        ),
        migrations.AddIndex(
            model_name='lotepos',
            index=models.Index(fields=['terminal', 'fecha_lote'], name='treasury_lo_termina_dc08d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lotepos',
            index=models.Index(fields=['fecha_lote', 'cuenta_bancaria'], name='treasury_lo_fecha_l_a2a109_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotepos',
            constraint=models.CheckConstraint(condition=models.Q(('total_lote__gt', 0)), name='pos_batch_total_positive'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['cuenta_bancaria', 'fecha'], name='treasury_mo_cuenta__d161b7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['tipo', 'fecha'], name='treasury_mo_tipo_f66260_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['origen', 'fecha'], name='treasury_mo_origen_f57d0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientobancario',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='bank_movement_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='acreditaciontarjeta',
            index=models.Index(fields=['canal', 'creado_en'], name='treasury_ac_canal_fb098f_idx'),
        ),
    ]
