# Generated by Django 5.2.6 on 2026-03-30 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_add_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acreditaciones_tarjeta_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentoacreditacion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='descuentoacreditacion',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_acreditacion_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotepos',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_pos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios_actualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
