# Generated by Django 5.2.6 on 2026-03-30 15:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_ep04_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Efectivo Central', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cajas Centrales',
            },
        ),
        migrations.CreateModel(
            name='ArqueoDisponibilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('saldo_sistema_efectivo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_contado_efectivo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos_realizados', to=settings.AUTH_USER_MODEL)),
                ('caja_central', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.cajacentral')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CierreMensualTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer dia del mes que se cierra')),
                ('saldo_inicial_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_final_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldos_bancarios_json', models.JSONField(default=dict, help_text='Dict {cuenta_id: saldo_final}')),
                ('cerrado', models.BooleanField(default=False)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_mensuales_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mes'],
                'constraints': [models.UniqueConstraint(fields=('mes',), name='unique_monthly_closing_per_month')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('INGRESO_CAJA', 'Ingreso desde Caja Operativa'), ('APORTE', 'Aporte de Socios/Capital'), ('RETIRO_BANCO', 'Retiro de Banco (Efectivo)'), ('EGRESO_PAGO', 'Egreso por Pago Administrativo'), ('DEPOSITO_BANCO', 'Deposito en Banco'), ('AJUSTE_POSITIVO', 'Ajuste de Saldo (+)'), ('AJUSTE_NEGATIVO', 'Ajuste de Saldo (-)')], max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(max_length=160)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja_central', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='treasury.cajacentral')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_central_creados', to=settings.AUTH_USER_MODEL)),
                ('movimiento_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_central', to='treasury.movimientobancario')),
                ('pago_tesoreria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_central', to='treasury.pagotesoreria')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='central_cash_movement_positive')],
            },
        ),
    ]
