# Generated by Django 5.2.6 on 2026-03-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_cajacentral_arqueodisponibilidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagotesoreria',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='treasury.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='pagotesoreria',
            name='medio_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('ECHEQ', 'ECHEQ'), ('EFECTIVO', 'Efectivo')], max_length=20),
        ),
    ]
