# Generated by Django 5.2.6 on 2026-03-30 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0006_movimientocaja_impacta_saldo_caja_and_more'),
        ('treasury', '0008_alter_pagotesoreria_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueodisponibilidades',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_disponibilidades', to='cashops.sucursal'),
        ),
        migrations.AddField(
            model_name='cajacentral',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_centrales', to='cashops.sucursal'),
        ),
        migrations.AddField(
            model_name='cierremensualtesoreria',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_mensuales_tesoreria', to='cashops.sucursal'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='cashops.sucursal'),
        ),
    ]
