# Generated by Django 5.2.6 on 2026-04-21 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_bank_movement_classes(apps, schema_editor):
    MovimientoBancario = apps.get_model('treasury', 'MovimientoBancario')

    for movement in MovimientoBancario.objects.select_related('pago_tesoreria').all():
        if movement.origen == MovimientoBancario.Origen.ACREDITACION_TARJETA:
            movement.clase = MovimientoBancario.Clase.ACREDITACION
        elif movement.origen == MovimientoBancario.Origen.PAGO_TESORERIA and movement.pago_tesoreria_id:
            if movement.pago_tesoreria.medio_pago == 'CHEQUE':
                movement.clase = MovimientoBancario.Clase.CHEQUE
            elif movement.pago_tesoreria.medio_pago == 'ECHEQ':
                movement.clase = MovimientoBancario.Clase.ECHEQ
            else:
                movement.clase = MovimientoBancario.Clase.TRANSFERENCIA_TERCEROS
        elif movement.tipo == MovimientoBancario.Tipo.CREDITO:
            movement.clase = MovimientoBancario.Clase.OTRO_INGRESO
        else:
            movement.clase = MovimientoBancario.Clase.OTRO_EGRESO
        movement.save(update_fields=['clase'])


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0011_proveedor_direccion_proveedor_sitio_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='modo_registro',
            field=models.CharField(choices=[('DIARIA', 'Carga diaria'), ('PERIODO', 'Carga agrupada por periodo')], default='DIARIA', max_length=10),
        ),
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='periodo_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acreditaciontarjeta',
            name='periodo_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='treasury.categoriacuentapagar'),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='clase',
            field=models.CharField(choices=[('ACREDITACION', 'Ingreso por acreditacion'), ('OTRO_INGRESO', 'Otro ingreso'), ('CHEQUE', 'Egreso por cheque'), ('ECHEQ', 'Egreso por ECHEQ'), ('IMPUESTO', 'Egreso por impuestos'), ('COMISION_BANCARIA', 'Egreso por comision bancaria'), ('RETIRO', 'Egreso por retiro'), ('TRANSFERENCIA_TERCEROS', 'Egreso por transferencia a terceros'), ('OTRO_EGRESO', 'Otro egreso')], default='OTRO_INGRESO', max_length=32),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='treasury.proveedor'),
        ),
        migrations.RunPython(backfill_bank_movement_classes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='acreditaciontarjeta',
            index=models.Index(fields=['modo_registro', 'periodo_desde', 'periodo_hasta'], name='treasury_ac_modo_re_68dc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['clase', 'fecha'], name='treasury_mo_clase_333cd8_idx'),
        ),
    ]
