# Generated by Django 5.2.6 on 2026-04-21 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_periodo_referencia(apps, schema_editor):
    CuentaPorPagar = apps.get_model("treasury", "CuentaPorPagar")

    for payable in CuentaPorPagar.objects.all().only("id", "fecha_emision", "fecha_vencimiento"):
        reference_date = payable.fecha_emision or payable.fecha_vencimiento
        if reference_date is None:
            continue
        payable.periodo_referencia = reference_date.replace(day=1)
        payable.save(update_fields=["periodo_referencia"])


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0008_sucursal_razon_social'),
        ('treasury', '0012_acreditaciontarjeta_modo_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacuentapagar',
            name='rubro_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_cuenta_pagar', to='cashops.rubrooperativo'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='periodo_referencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_periodo_referencia, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['periodo_referencia', 'sucursal'], name='treasury_cu_periodo_5ed30a_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagar',
            index=models.Index(fields=['periodo_referencia', 'categoria'], name='treasury_cu_periodo_d67143_idx'),
        ),
    ]
