# Generated by Django 5.2.6 on 2026-04-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0013_ep11_rubro_period_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='periodo_referencia',
            field=models.DateField(),
        ),
    ]
