# Generated by Django 5.2.6 on 2026-04-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0008_sucursal_razon_social'),
        ('treasury', '0014_ep11_period_reference_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoRubroEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_rubro_economico_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_rubro_economico_creados', to=settings.AUTH_USER_MODEL)),
                ('rubro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_economicos', to='cashops.rubrooperativo')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_rubro_economico', to='cashops.sucursal')),
            ],
            options={
                'ordering': ['rubro_operativo__nombre', 'sucursal__nombre', '-vigencia_desde', 'id'],
                'indexes': [models.Index(fields=['activo', 'vigencia_desde', 'vigencia_hasta'], name='treasury_ob_activo_64dbf9_idx'), models.Index(fields=['rubro_operativo', 'sucursal', 'vigencia_desde'], name='treasury_ob_rubro_o_6f1a1c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje_objetivo__gt', 0)), name='economic_target_percentage_positive'), models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), ('vigencia_hasta__gte', models.F('vigencia_desde')), _connector='OR'), name='economic_target_end_after_start'), models.UniqueConstraint(fields=('rubro_operativo', 'sucursal', 'vigencia_desde'), name='unique_economic_target_start_per_scope')],
            },
        ),
    ]
