# Generated by Django 5.2.6 on 2026-04-24 14:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0008_sucursal_razon_social'),
        ('treasury', '0015_objetivorubroeconomico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromisoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMPUESTO', 'Impuesto u obligacion fiscal'), ('PLAN_PAGO', 'Plan de pago / cuota'), ('REQUERIMIENTO', 'Requerimiento pendiente'), ('ADELANTO', 'Adelanto autorizado'), ('EMBARGO', 'Embargo o retencion judicial'), ('SUELDO_EXTRAORDINARIO', 'Sueldo extraordinario')], max_length=32)),
                ('concepto', models.CharField(max_length=160)),
                ('organismo', models.CharField(blank=True, max_length=120)),
                ('beneficiario', models.CharField(blank=True, max_length=160)),
                ('expediente', models.CharField(blank=True, max_length=80)),
                ('sustento_referencia', models.CharField(max_length=120)),
                ('periodo_fiscal', models.DateField(blank=True, null=True)),
                ('fecha_compromiso', models.DateField(default=django.utils.timezone.localdate)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBACION_PENDIENTE', 'Aprobacion pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EJECUTADO', 'Ejecutado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=24)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('plan_nombre', models.CharField(blank=True, max_length=120)),
                ('numero_cuota', models.PositiveIntegerField(blank=True, null=True)),
                ('total_cuotas', models.PositiveIntegerField(blank=True, null=True)),
                ('capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('interes_financiero', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('interes_resarcitorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('comentario_autorizacion', models.CharField(blank=True, max_length=255)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_especiales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_especiales_autorizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos_especiales_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_por_pagar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromiso_especial', to='treasury.cuentaporpagar')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_especiales', to='cashops.sucursal')),
            ],
            options={
                'ordering': ['vencimiento', 'fecha_compromiso', 'id'],
                'indexes': [models.Index(fields=['tipo', 'estado', 'vencimiento'], name='treasury_co_tipo_08577d_idx'), models.Index(fields=['sucursal', 'vencimiento'], name='treasury_co_sucursa_a5ae05_idx'), models.Index(fields=['plan_nombre', 'numero_cuota'], name='treasury_co_plan_no_3f05a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto_estimado__gt', 0)), name='special_commitment_amount_positive'), models.CheckConstraint(condition=models.Q(('capital__gte', 0)), name='special_commitment_capital_non_negative'), models.CheckConstraint(condition=models.Q(('interes_financiero__gte', 0)), name='special_commitment_financial_interest_non_negative'), models.CheckConstraint(condition=models.Q(('interes_resarcitorio__gte', 0)), name='special_commitment_resarcitory_interest_non_negative')],
            },
        ),
    ]
