# Generated by Django 5.2.6 on 2026-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0019_bank_movement_annulment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='clase',
            field=models.CharField(choices=[('ACREDITACION', 'Ingreso por acreditación'), ('OTRO_INGRESO', 'Otro ingreso'), ('CHEQUE', 'Egreso por cheque'), ('ECHEQ', 'Egreso por ECHEQ'), ('IMPUESTO', 'Egreso por impuestos'), ('COMISION_BANCARIA', 'Egreso por comisión bancaria'), ('RETIRO', 'Egreso por retiro'), ('TRANSFERENCIA_TERCEROS', 'Egreso por transferencia a terceros'), ('OTRO_EGRESO', 'Otro egreso')], default='OTRO_INGRESO', max_length=32),
        ),
        migrations.AlterField(
            model_name='movimientocajacentral',
            name='tipo',
            field=models.CharField(choices=[('INGRESO_CAJA', 'Ingreso desde Caja Operativa'), ('APORTE', 'Aporte de Socios/Capital'), ('RETIRO_BANCO', 'Retiro de Banco (Efectivo)'), ('EGRESO_PAGO', 'Egreso por Pago Administrativo'), ('EGRESO_ADMIN', 'Egreso Administrativo de Tesorería'), ('DEPOSITO_BANCO', 'Depósito en Banco'), ('AJUSTE_POSITIVO', 'Ajuste de Saldo (+)'), ('AJUSTE_NEGATIVO', 'Ajuste de Saldo (-)')], max_length=40),
        ),
    ]
