# Generated by Django 5.2.6 on 2026-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0020_alter_movimientobancario_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ACREDITACION_TARJETA', 'Acreditacion tarjeta'), ('PAGO_TESORERIA', 'Pago tesoreria'), ('EGRESO_TESORERIA', 'Egreso tesoreria')], default='MANUAL', max_length=24),
        ),
    ]
