# Generated by Django 5.2.6 on 2026-07-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0020_alter_caja_estado_cajacorreccion'),
        ('treasury', '0021_bank_treasury_expense_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='cashops.empresa'),
        ),
    ]
