# Generated by Django 5.2.6 on 2026-07-14 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0021_cajavalidacion_caja_validacion_estado_and_more'),
        ('treasury', '0023_backfill_cuenta_bancaria_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='caja_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_originadas', to='cashops.caja'),
        ),
    ]
