# Generated by Django 5.2.6 on 2026-07-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0021_cajavalidacion_caja_validacion_estado_and_more'),
        ('treasury', '0024_cuentaporpagar_caja_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocajacentral',
            name='caja_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_centrales_de_cierre', to='cashops.caja'),
        ),
    ]
