# Generated by Django 5.2.6 on 2026-07-25 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0021_cajavalidacion_caja_validacion_estado_and_more'),
        ('treasury', '0025_movimientocajacentral_caja_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='cuentaporpagar',
            name='unique_payable_reference_by_supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_comprobante', ''), _negated=True), fields=('proveedor', 'referencia_comprobante'), name='unique_payable_reference_by_supplier', violation_error_message='Ya existe una deuda cargada con esa referencia/comprobante para este proveedor.'),
        ),
    ]
