# Generated by Django 5.2.6 on 2026-07-26 02:10

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0022_remove_caja_unique_open_box_by_user_turn_branch_and_more'),
        ('treasury', '0026_alter_cuentaporpagar_unique_payable_reference_by_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='categoriacuentapagar',
            name='unique_payable_category_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_payable_category_name_ci', violation_error_message='Ya existe una categoría de gasto con ese nombre.'),
        ),
        migrations.AlterConstraint(
            model_name='cierremensualtesoreria',
            name='unique_monthly_closing_per_month',
            constraint=models.UniqueConstraint(fields=('mes',), name='unique_monthly_closing_per_month', violation_error_message='Ese mes ya tiene un cierre mensual de tesorería.'),
        ),
        migrations.AlterConstraint(
            model_name='compromisoespecial',
            name='special_commitment_amount_positive',
            constraint=models.CheckConstraint(condition=models.Q(('monto_estimado__gt', 0)), name='special_commitment_amount_positive', violation_error_message='El monto estimado del compromiso debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='compromisoespecial',
            name='special_commitment_capital_non_negative',
            constraint=models.CheckConstraint(condition=models.Q(('capital__gte', 0)), name='special_commitment_capital_non_negative', violation_error_message='El capital no puede ser negativo.'),
        ),
        migrations.AlterConstraint(
            model_name='compromisoespecial',
            name='special_commitment_financial_interest_non_negative',
            constraint=models.CheckConstraint(condition=models.Q(('interes_financiero__gte', 0)), name='special_commitment_financial_interest_non_negative', violation_error_message='El interés financiero no puede ser negativo.'),
        ),
        migrations.AlterConstraint(
            model_name='compromisoespecial',
            name='special_commitment_resarcitory_interest_non_negative',
            constraint=models.CheckConstraint(condition=models.Q(('interes_resarcitorio__gte', 0)), name='special_commitment_resarcitory_interest_non_negative', violation_error_message='El interés resarcitorio no puede ser negativo.'),
        ),
        migrations.AlterConstraint(
            model_name='cuentabancaria',
            name='unique_bank_account_cbu_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('cbu'), condition=models.Q(('cbu', ''), _negated=True), name='unique_bank_account_cbu_ci', violation_error_message='Ya existe una cuenta bancaria con ese CBU.'),
        ),
        migrations.AlterConstraint(
            model_name='cuentabancaria',
            name='unique_bank_account_number_per_bank',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('banco'), models.F('numero_cuenta'), name='unique_bank_account_number_per_bank', violation_error_message='Ya existe una cuenta con ese número en ese banco.'),
        ),
        migrations.AlterConstraint(
            model_name='cuentaporpagar',
            name='payable_total_positive',
            constraint=models.CheckConstraint(condition=models.Q(('importe_total__gt', 0)), name='payable_total_positive', violation_error_message='El importe total de la deuda debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='cuentaporpagar',
            name='payable_balance_non_negative',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', 0)), name='payable_balance_non_negative', violation_error_message='El saldo pendiente de la deuda no puede ser negativo.'),
        ),
        migrations.AlterConstraint(
            model_name='cuentaporpagar',
            name='payable_balance_lte_total',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__lte', models.F('importe_total'))), name='payable_balance_lte_total', violation_error_message='El saldo pendiente no puede superar el importe total de la deuda.'),
        ),
        migrations.AlterConstraint(
            model_name='cuentaporpagar',
            name='payable_due_after_issue',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gte', models.F('fecha_emision'))), name='payable_due_after_issue', violation_error_message='La fecha de vencimiento no puede ser anterior a la fecha de factura.'),
        ),
        migrations.AlterConstraint(
            model_name='descuentoacreditacion',
            name='accreditation_discount_amount_positive',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='accreditation_discount_amount_positive', violation_error_message='El monto del descuento debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='lotepos',
            name='pos_batch_total_positive',
            constraint=models.CheckConstraint(condition=models.Q(('total_lote__gt', 0)), name='pos_batch_total_positive', violation_error_message='El total del lote POS debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='movimientobancario',
            name='bank_movement_amount_positive',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='bank_movement_amount_positive', violation_error_message='El monto del movimiento bancario debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='movimientocajacentral',
            name='central_cash_movement_positive',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='central_cash_movement_positive', violation_error_message='El monto del movimiento de caja central debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='objetivorubroeconomico',
            name='economic_target_percentage_positive',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_objetivo__gt', 0)), name='economic_target_percentage_positive', violation_error_message='El porcentaje objetivo debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='objetivorubroeconomico',
            name='economic_target_end_after_start',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), ('vigencia_hasta__gte', models.F('vigencia_desde')), _connector='OR'), name='economic_target_end_after_start', violation_error_message='La vigencia hasta no puede ser anterior a la vigencia desde.'),
        ),
        migrations.AlterConstraint(
            model_name='objetivorubroeconomico',
            name='unique_economic_target_start_per_scope',
            constraint=models.UniqueConstraint(fields=('rubro_operativo', 'sucursal', 'vigencia_desde'), name='unique_economic_target_start_per_scope', violation_error_message='Ya existe un objetivo para ese rubro y alcance con la misma fecha de inicio.'),
        ),
        migrations.AlterConstraint(
            model_name='pagotesoreria',
            name='treasury_payment_amount_positive',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='treasury_payment_amount_positive', violation_error_message='El monto del pago debe ser mayor que cero.'),
        ),
        migrations.AlterConstraint(
            model_name='pagotesoreria',
            name='unique_payment_reference_per_bank_method',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia', ''), _negated=True), fields=('cuenta_bancaria', 'medio_pago', 'referencia'), name='unique_payment_reference_per_bank_method', violation_error_message='Ya existe un pago con esa referencia para esa cuenta bancaria y medio de pago.'),
        ),
        migrations.AlterConstraint(
            model_name='proveedor',
            name='unique_supplier_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('razon_social'), name='unique_supplier_name_ci', violation_error_message='Ya existe un proveedor con esa razón social.'),
        ),
        migrations.AlterConstraint(
            model_name='proveedor',
            name='unique_supplier_tax_id_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('identificador_fiscal'), condition=models.Q(('identificador_fiscal', ''), _negated=True), name='unique_supplier_tax_id_ci', violation_error_message='Ya existe un proveedor con ese identificador fiscal (CUIT).'),
        ),
        migrations.AlterConstraint(
            model_name='saldoinicialcuentabancaria',
            name='unique_initial_bank_balance_per_account_date',
            constraint=models.UniqueConstraint(fields=('cuenta_bancaria', 'fecha_referencia'), name='unique_initial_bank_balance_per_account_date', violation_error_message='Ya existe un saldo inicial para esa cuenta y fecha.'),
        ),
    ]
