# Generated by Django 5.2.6 on 2026-07-27 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0024_movimientocaja_token_alta_and_more'),
        ('treasury', '0027_alter_categoriacuentapagar_unique_payable_category_name_ci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='token_alta',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token de alta'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.UniqueConstraint(condition=models.Q(('token_alta__isnull', False)), fields=('token_alta',), name='unique_payable_creation_token', violation_error_message='Esta deuda ya fue registrada.'),
        ),
    ]
