# Generated by Django 5.2.6 on 2026-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0028_cuentaporpagar_token_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='generado_por_pago',
            field=models.BooleanField(default=False),
        ),
    ]
