# Generated by Django 5.2.6 on 2026-07-31 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0024_movimientocaja_token_alta_and_more'),
        ('treasury', '0032_unique_boveda_por_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocajacentral',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocajacentral',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_central_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocajacentral',
            name='estado',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=12),
        ),
        migrations.AddField(
            model_name='movimientocajacentral',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientocajacentral',
            name='reversa_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversas', to='treasury.movimientocajacentral'),
        ),
        migrations.AddIndex(
            model_name='movimientocajacentral',
            index=models.Index(fields=['caja_central', 'estado'], name='treasury_mo_caja_ce_67ae8f_idx'),
        ),
    ]
