# Generated by Django 5.2.6 on 2026-08-03 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashops', '0026_alter_cajavalidacion_accion'),
        ('treasury', '0034_cierre_mensual_por_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='token_alta',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token de alta'),
        ),
        migrations.AddField(
            model_name='movimientocajacentral',
            name='token_alta',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token de alta'),
        ),
        migrations.AddField(
            model_name='pagotesoreria',
            name='token_alta',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token de alta'),
        ),
        migrations.AddConstraint(
            model_name='movimientobancario',
            constraint=models.UniqueConstraint(condition=models.Q(('token_alta__isnull', False)), fields=('token_alta',), name='unique_bank_movement_creation_token', violation_error_message='Este movimiento bancario ya fue registrado.'),
        ),
        migrations.AddConstraint(
            model_name='movimientocajacentral',
            constraint=models.UniqueConstraint(condition=models.Q(('token_alta__isnull', False)), fields=('token_alta',), name='unique_central_cash_creation_token', violation_error_message='Este movimiento de caja fuerte ya fue registrado.'),
        ),
        migrations.AddConstraint(
            model_name='pagotesoreria',
            constraint=models.UniqueConstraint(condition=models.Q(('token_alta__isnull', False)), fields=('token_alta',), name='unique_payment_creation_token', violation_error_message='Este pago ya fue registrado.'),
        ),
    ]
